# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8488e1aed12aa76c0311f5609668deefa48d53980c06e08f8dd99393764d1a70c341bcb3b59050f8da3a376cb392386777e7735c77c302683faa3875ac08f3a

test:
  secret_key_base: 5169f6fb85bdbe0443a672f0307d61198a1b58392749f0c4780788cd2601953eb66720846b68cec6c8909cbac369e3830857033f381c9ad5e7878e90049e1df2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
